### ISSUE TITLE
how to run the program

### ISSUE THREAD

**Issue by Alisaincd** [erickrf/autoencoder#1]
hi,I'm interested in this project.But I got a problem when I run it. I have some questions:

1. What is the format of the input data?My input like this: 我 是 一个 小孩（Chinese words splited by whitespace）Is it right?
2. In the second step,I run this command:
python train-autoencoder.py /model data/vocabulary.txt data/train-data.npz data/valid-data.npz，but there is no model is saved in the directory '/model'. Can you tell me the reason?

I will really appreciate it if you can answer my questions.Thank you for you patience!

**Comment by erickrf** [comment]
1. Yes, the input tokens should be separated by whitespace. 
2. Are you sure you ran used `/model`, with a `/`? This would need a model folder in the root of your filesystem. The normal way would be just `model` in the project directory.

**Comment by Alisaincd** [comment]
Sorry, it's 'model/',not '/model', I just wrote wrong.I checked it again and rerun it, but the model still can't be saved.The model directory is empty.I will check again later. If you find anything may be useful,please let me know. Thank you very much!

**Comment by erickrf** [comment]
This is strange. Are you getting any output when you run the script?

**Comment by Alisaincd** [comment]
Yeah,the output indicates that there is really a model was trained.
<img width="811" alt="2017-02-08 9 55 43" src="https://cloud.githubusercontent.com/assets/11712829/22742883/394422f8-edcd-11e6-86ba-807803902d66.png">

**Comment by erickrf** [comment]
In your output, the model wasn't saved yet. At each report interval (defined with `-i`), you see partial training statistics, the model runs on validation data and is saved if the loss decreased.
