### ISSUE TITLE
Multilayered LSTM

### ISSUE THREAD

**Issue by richielo** [erickrf/autoencoder#10]
Hello @erickrf ,

Thanks for the great reference implementation. I noticed that the paper mentioned that they have 4 layers of LSTMs. Is this adopted in your code? I am not sure which are the 4 layers. Is it 3 for encoder and 1 for decoder? Sorry if I understood it incorrectly. Thanks!

**Comment by erickrf** [comment]
Hi, the implementation only has one layer. It was not supposed to implement the exact architecture in the Sutskever paper.
