### ISSUE TITLE
what to feed as input for decoder

### ISSUE THREAD

**Issue by zhang-yu-wei** [erickrf/autoencoder#12]
Hi~, I am using your software now. I think that's exactly what I want at the moment. But there is still a problem that seems quite confusing. That is I notice you are using the embedded input sentence to feed decoder. But in the article https://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf, they are using the output at each timestep as the input for next timestep. Have I misunderstood your code or you are not doing what's going on in the article.

**Comment by erickrf** [comment]
You are right, the decoder is trained with the correct sequence as input. At running time however, the input at time step `t + 1` is the output produced by the decoder at time step `t`.
