### ISSUE TITLE
How do I choose embedding_size

### ISSUE THREAD

**Issue by zhang-yu-wei** [erickrf/autoencoder#14]
Thanks for explanation last time. But I am still thinking about how to set up embedding size, is it a really bad thing when it is set to only 1 or 2 ?

**Comment by erickrf** [comment]
Yes, it is. The embeddings should be large enough to map similarities and differences of words in the embedding space. Reasonable values are at least 50, with 100, 200 or 300 being common too. But that also depends on the amount of data you have and the vocabulary size -- the larger they are, the more dimensions your embeddings should have.
