### ISSUE TITLE
Is there a way to decode the vectors into words?

### ISSUE THREAD

**Issue by zhang-yu-wei** [erickrf/autoencoder#16]
Hi, I understand you are using the state.c as a representation of the sentences, but suppose I can get a state.c without knowing anything about the sentence, is there a way to decode it into the sentence?

**Comment by erickrf** [comment]
That's what the decoder part does, and the code is mostly inside the `run()` function.

**Comment by zhang-yu-wei** [comment]
So the situation is I want to use the encoded states to represent sentences, and input them to a certain neural net, so that it can give me a vector which is a encoded sentence, and I need to translate it into a real sentence. I don't think there is a function like already, can you please give me some advice?

**Comment by erickrf** [comment]
I didn't understand very well. The script `codify-sentences.py` does the first part of what you mentioned, it creates vectors representing sentences. These vectors can be used in other models to classify them, cluster, or do whatever other task.
