### ISSUE TITLE
not expected output

### ISSUE THREAD

**Issue by ghost** [erickrf/autoencoder#17]
python interactive.py /home/acer/PycharmProjects/VAE_MODEL/autoencoder-master/src/save_dir /home/acer/PycharmProjects/VAE_MODEL/autoencoder-master/src/save/vocabulary.txt
INFO:root:Reading model
2018-12-18 22:47:29.512330: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Restoring parameters from /home/acer/PycharmProjects/VAE_MODEL/autoencoder-master/src/save_dir/model
INFO:tensorflow:Restoring parameters from /home/acer/PycharmProjects/VAE_MODEL/autoencoder-master/src/save_dir/model
Type tokenized sentence: i am an AI Engineer
Model output: a a a a a a a a a a a a
Type tokenized sentence:

**Comment by erickrf** [comment]
This can happen if the model hasn't learned well. You must train the autoencoder longer until its loss is lower (I think at 0.1 you can have some reasonable results).
