### ISSUE TITLE
text classification 

### ISSUE THREAD

**Issue by Rgui** [erickrf/autoencoder#19]
Hi and thanks for the nice project. 
I have never used autoencoders, so forgive my ignorance.
Questions:
1 - Can I use your code to classify a text into 2 categories ? - I have a dataset where 1st column contains 1 sentence and 2nd column a category, either 0 or 1. 
2. If yes to Question 1, how should the train and test data look?

**Comment by erickrf** [comment]
The autoencoder does not do any classification. It is just a way to create sentence representations, which might be used as input by a classifier, but you would have to create that classifier.
