### ISSUE TITLE
applying on 20 news group dataset

### ISSUE THREAD

**Issue by un-lock-me** [erickrf/autoencoder#21]
Hi,

I would like to apply your code on 20 newsgroup data set, but I am not sure how can I change the prepare data?

my problem mainly is in preparing labels. how it can be different from yours when it apply on 20 newsgroup data set?

Thanks for your help:)

**Comment by erickrf** [comment]
It depends on what exactly you want to do. If you want to use a pretrained autoencoder, you will have just to load the pretrained weights to a classifier of the newsgroups.
