### ISSUE TITLE
a question about line124 in autoencoder.py

### ISSUE THREAD

**Issue by sodawater** [erickrf/autoencoder#4]
https://github.com/erickrf/autoencoder/blob/6c0aa772484c804f31cdf72a3fd074c06a57fd18/src/autoencoder.py#L124

why not  "decoder_input = list_input + [embedded_eos]" ?
The symbol EOS supposes to mark the end of the sentence.

**Comment by erickrf** [comment]
It might be a bit confusing looking at that line in isolation. The EOS at the beginning of the decoder input signals that the input sentence is finished (the EOS isn't given to the encoder), so after seeing it, the network can start outputting the words.

**Comment by sodawater** [comment]
Got it. Thanks.
