### ISSUE TITLE
raise TypeError("Cannot convert {} to a dtype. {}".format(type_value, e))

### ISSUE THREAD

**Issue by Hazel1994** [erickrf/autoencoder#5]
hi  , so am using tensorflow1.0 on python 3.5.2 on windows ,ive successfully run "prepare-data.py" but when am running "train-autoencoder.py" i get the following error 

` raise TypeError("Cannot convert {} to a dtype. {}".format(type_value, e))`
`TypeError: Cannot convert (19528,) to a dtype. data type not understood`
 
i think its because of the initializer so i changed "initializer = tf.zeros_initializer((self.vocab_size,))"
to "initializer = tf.zeros_initializer" and It worked but i get another error when it tries to use the "projection_b" variable , seems like we have to specify the shape of it 
"Shape of a new variable (autoencoder/projection_b) must be fully defined, but instead was <unknown>."
i dont know how to fix this one ,i really appreciate it if anyone could help me , thanks

**Comment by iosifidisvasileios** [comment]
I have the same issue. I constructed the external files based on my corpus (each sentence is separated by newline) and afterwards I tried to train the auto-encoder without providing initial word embeddings.  Also while creating the external files I did not specify the maximum size of sentences.
I get the same error as @Hazel1994 

Traceback (most recent call last):
  File "train-autoencoder.py", line 113, in <module>
    bidirectional=args.bidirectional)
  File "/home/iosifidis/PycharmProjects/autoencoder/src/autoencoder.py", line 84, in __init__
    initializer = tf.zeros_initializer((self.vocab_size,))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/init_ops.py", line 88, in __init__
    self.dtype = dtypes.as_dtype(dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/dtypes.py", line 581, in as_dtype
    raise TypeError("Cannot convert {} to a dtype. {}".format(type_value, e))
TypeError: Cannot convert (25934,) to a dtype. data type not understood

**Comment by erickrf** [comment]
I'm rather busy this week, but I'll try to have a look at it in the next days.

**Comment by chued** [comment]
Tried a bit of debugging, but eventually just rolled back tensorflow to 0.12.0rc1. Looks like there were breaking changes in 1.0 involving renaming and/or reordering of parameters.

After resolving the type error in autoencoder.py line 84, it fails next on L117 with a lower level call to tf.split in 193.

> tf.split now takes arguments in a reversed order and with different keywords. In particular, we now match NumPy order as tf.split(value, num_or_size_splits, axis).

From:
https://github.com/tensorflow/tensorflow/issues/6501
https://github.com/tensorflow/models/issues/933

I didn't keep that detailed a log of my steps, so sorry if I missed one. Hope this saves y'all some time.

**Comment by zjwzcn07** [comment]
You can replace line84 with following  @Hazel1994 @iosifidisvasileios  :
`initializer = tf.zeros_initializer()`
`self.projection_b = tf.get_variable('projection_b',shape = (self.vocab_size),initializer=initializer)`

**Comment by iosifidisvasileios** [comment]
@zjwzcn07 I moderated the lines you indicated. The thing is that now it crashes at:
```
Traceback (most recent call last):
  File "train-autoencoder.py", line 113, in <module>
    bidirectional=args.bidirectional)
  File "/home/iosifidis/PycharmProjects/autoencoder/src/autoencoder.py", line 122, in __init__
    list_input = self._tensor_to_list(embedded)
  File "/home/iosifidis/PycharmProjects/autoencoder/src/autoencoder.py", line 198, in _tensor_to_list
    for step in tf.split(1, num_steps, tensor)]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1232, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3490, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 513, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

```
I think that if I try to moderate the tensor to 'int32' it will have really bad results.

**Comment by iosifidisvasileios** [comment]
In the end I just rolled back to tf 0.12 instead of 0.13 and it runs smoothly.

**Comment by zjwzcn07** [comment]
@iosifidisvasileios  Due to the version compatibility, you can fix code(Line193) from
`       
 return [tf.squeeze(step, [1])
                for step in tf.split(1, num_steps, tensor)]
`
to
`
 return [tf.squeeze(step, [1])
                for step in tf.split(tensor, num_steps, 1)]
`
The latter support tf1.2.1 .

BTW, I think the version compatibility of TF is really disgusting.

**Comment by CMWENLIU** [comment]
@zjwzcn07 
I replaced the Line 193 with what you said, but it is still the same problem.

**Comment by NicMcPhee** [comment]
Is this just completely borked because of breaking updates to TensorFlow? It looks like it would be useful, but it throws buckets of errors for me and it's unclear whether it's worth trying to get this to work, or just moving on to other options.

**Comment by erickrf** [comment]
Mostly yes, because of tensorflow. I stopped working with autoencoders but
plan to take it again in the next week or so.

Em dom, 8 de abr de 2018 15:43, Nic McPhee <notifications@github.com>
escreveu:

**Comment by erickrf** [comment]
I've rewritten a good deal of the code and it runs fine on tensorflow 1.7.
