### ISSUE TITLE
Minor bug in prepare-data.py

### ISSUE THREAD

**Issue by roozbehataisera** [erickrf/autoencoder#7]
Happy to do a pull request by basically:
```
     train_data, valid_data, words = load_data_memory_friendly(args.input,
                                                               args.max_length,
                                                               args.min_freq)
```
Needs to be replaced by
```
     train_data, valid_data, words = load_data_memory_friendly(args.input,
                                                               args.max_length,
                                                               args.min_freq,
                                                               args.valid_proportion)
```

Also, I made the code compatible with Python3. Let me know if you are interested.

**Comment by erickrf** [comment]
That is great. Please do submit the PR.

**Comment by roozbehataisera** [comment]
When tried to push my fix branch I got:
fatal: unable to access 'https://github.com/erickrf/autoencoder.git/': The
requested URL returned error: 403

**Comment by erickrf** [comment]
It seems you are trying to push directly to this repository. The procedure I know to submit pull requests is to:

1. Fork the repository
2. Push the changes to your fork
3. Submit a pull request in the original repository

**Comment by erickrf** [comment]
The new commit apparently runs fine in py3. The fix was incorporated.
