### ISSUE TITLE
Model Saving Problem

### ISSUE THREAD

**Issue by EMehralian** [erickrf/autoencoder#8]
Hello, I have tried to train a model but I got the following exception while saving the model:

    autoencoder/embeddings:0: (1380, 300) (414000 parameters)
    autoencoder/fw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
    autoencoder/fw/lstm_cell/bias:0: (2000,) (2000 parameters)
    autoencoder/bw/lstm_cell/kernel:0: (800, 2000) (1600000 parameters)
    autoencoder/bw/lstm_cell/bias:0: (2000,) (2000 parameters)
    projection/dense/kernel:0: (1000, 1380) (1380000 parameters)
    projection/dense/bias:0: (1380,) (1380 parameters)
    Total: 4999380 parameters
    INFO:root:Initialized the model and all variables. Starting training.
    Traceback (most recent call last):
      File "train-autoencoder.py", line 113, in <module>
        args.dropout_keep, 5.0, report_interval=args.interval)
      File "/autoencoder-master/src/autoencoder.py", line 285, in train
        self.save(saver, session, save_path)
      File "/autoencoder-master/src/autoencoder.py", line 305, in save
        json.dump(metadata, f)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 180, in dump
        fp.write(chunk)
     TypeError: a bytes-like object is required, not 'str'

Do you have any idea?
Thanks

**Comment by erickrf** [comment]
It's probably because the file opened in line 305 in autoencoder.py is in 'wb' mode, and in Python 3 json expects the non-binary mode 'w'. 

You can change this line in your code, once I have the time I'll try to adapt the whole repository to Python 3.
